stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - src/clean_data.py
      - data/Sleep_health_and_lifestyle_dataset.csv
    outs:
      - data/cleaned_data.csv

  remove_duplicates:
    cmd: python src/remove_duplicates.py
    deps:
      - src/remove_duplicates.py
      - data/cleaned_data.csv
    outs:
      - data/remduplicated_data.csv