name: DVC Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dvc-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi\

    - name: Configure DVC with Google Drive Service Account
      env:
        GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > /tmp/service-account.json
        dvc remote modify --local myremote gdrive_service_account_json_file_path /tmp/service-account.json

    - name: Pull DVC data
      run: |
        dvc pull --force

    - name: Run DVC pipeline
      run: |
        dvc repro

    - name: Push DVC data
      run: |
        dvc push